// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService is the game library, as the frontend sees it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as meta$0 from "../meta/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enrich$0 from "../store/enrich/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArtChoices finds the pictures a game's cover, backdrop, hero or logo
 * could be (kind), stored and ready to show; the current one comes first.
 * It asks the stores, so it can take a few seconds.
 */
export function ArtChoices(id: number, kind: string): $CancellablePromise<meta$0.Choice[] | null> {
    return $Call.ByID(697163200, id, kind);
}

/**
 * ChooseExe lets the user pick the executable that starts the game.
 */
export function ChooseExe(id: number): $CancellablePromise<library$0.Game> {
    return $Call.ByID(1621179858, id);
}

/**
 * Completion is a game's completion times: cached ones at once, fetched
 * first when fetch is set and they're missing or older than seven days.
 * A failure keeps cached times (stale) or says they're unavailable.
 */
export function Completion(id: number, fetch: boolean): $CancellablePromise<$models.LibraryCompletion> {
    return $Call.ByID(2170273181, id, fetch);
}

/**
 * CompletionCandidates searches HowLongToBeat for the game's other
 * possible matches ("" searches its title).
 */
export function CompletionCandidates(id: number, query: string): $CancellablePromise<enrich$0.Candidate[] | null> {
    return $Call.ByID(1083826883, id, query);
}

/**
 * ConfirmMatch accepts the game's identity, so it no longer waits for a check in New on this PC.
 */
export function ConfirmMatch(id: number): $CancellablePromise<library$0.Game> {
    return $Call.ByID(2550635910, id);
}

/**
 * Game returns one game.
 */
export function Game(id: number): $CancellablePromise<library$0.Game> {
    return $Call.ByID(3258190977, id);
}

/**
 * Games returns every game in the library.
 */
export function Games(): $CancellablePromise<library$0.Game[] | null> {
    return $Call.ByID(2851102966);
}

/**
 * Install asks the game's store to install it (owned, not installed).
 */
export function Install(id: number): $CancellablePromise<void> {
    return $Call.ByID(3864775490, id);
}

/**
 * MetaState reports metadata fetching progress.
 */
export function MetaState(): $CancellablePromise<$models.MetaState> {
    return $Call.ByID(3704126675);
}

/**
 * OpenCompletionLink opens a HowLongToBeat link in the browser.
 */
export function OpenCompletionLink(raw: string): $CancellablePromise<void> {
    return $Call.ByID(3519112021, raw);
}

/**
 * OpenFolder shows the game's folder in Explorer.
 */
export function OpenFolder(id: number): $CancellablePromise<void> {
    return $Call.ByID(1976215147, id);
}

/**
 * RefreshMetadata fetches a game's metadata and art again.
 */
export function RefreshMetadata(id: number): $CancellablePromise<void> {
    return $Call.ByID(3269451891, id);
}

/**
 * Rename sets the title shown for a game ("" restores the found one).
 */
export function Rename(id: number, title: string): $CancellablePromise<library$0.Game> {
    return $Call.ByID(2404438665, id, title);
}

/**
 * RenameCollection renames a collection in every game; an empty name
 * deletes it (the games stay).
 */
export function RenameCollection(old: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3994719709, old, name);
}

/**
 * Rescan looks for games again now.
 */
export function Rescan(): $CancellablePromise<void> {
    return $Call.ByID(3200454951);
}

/**
 * ScanState reports what the scanner is doing.
 */
export function ScanState(): $CancellablePromise<$models.ScanState> {
    return $Call.ByID(1138768279);
}

/**
 * SearchSteam looks up titles on the Steam store, to pick the right game.
 */
export function SearchSteam(query: string): $CancellablePromise<meta$0.StoreHit[] | null> {
    return $Call.ByID(2831298449, query);
}

/**
 * SetArt makes a picture from ArtChoices the game's cover, backdrop, hero
 * or logo, kept through later refreshes.
 */
export function SetArt(id: number, kind: string, art: string): $CancellablePromise<library$0.Game> {
    return $Call.ByID(2120409302, id, kind, art);
}

/**
 * SetCollections puts a game in these collections (and out of others).
 */
export function SetCollections(id: number, names: string[] | null): $CancellablePromise<library$0.Game> {
    return $Call.ByID(630414306, id, names);
}

/**
 * SetCompletionMatch makes hltbID the game's match, shared with the
 * Store's page for the same game (0 goes back to the automatic match).
 */
export function SetCompletionMatch(id: number, hltbID: number): $CancellablePromise<$models.LibraryCompletion> {
    return $Call.ByID(16822812, id, hltbID);
}

/**
 * SetFavorite marks or unmarks a favorite.
 */
export function SetFavorite(id: number, on: boolean): $CancellablePromise<library$0.Game> {
    return $Call.ByID(1893656129, id, on);
}

/**
 * SetHidden hides a game from the library views (or shows it again).
 */
export function SetHidden(id: number, on: boolean): $CancellablePromise<library$0.Game> {
    return $Call.ByID(775406597, id, on);
}

/**
 * SetMatch says which game this is: a Steam app and its name. The choice
 * is kept across scans, and metadata is fetched for it.
 */
export function SetMatch(id: number, steamAppID: number, name: string): $CancellablePromise<library$0.Game> {
    return $Call.ByID(3387719082, id, steamAppID, name);
}

/**
 * SetPadMode picks how a controller reaches the game: "" (auto), "native" or "steam".
 */
export function SetPadMode(id: number, mode: string): $CancellablePromise<library$0.Game> {
    return $Call.ByID(880089469, id, mode);
}
