// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as achievements$0 from "../achievements/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncer$0 from "../syncer/models.js";

/**
 * Accounts are the store accounts owned games come from.
 */
export interface Accounts {
    "steam": StoreAccount;
    "gog": StoreAccount;
    "epic": StoreAccount;

    /**
     * GOGSignIn is the GOG account signed in for achievements (GOG
     * Galaxy's library, above, needs no sign-in).
     */
    "gogSignIn": StoreAccount;
}

/**
 * AppInfo describes this build.
 */
export interface AppInfo {
    "version": string;
    "dataDir": string;
    "logFile": string;

    /**
     * The previous run crashed (its output is in crash-previous.log).
     */
    "crashedLastTime": boolean;
}

/**
 * EngineStatus is the download engine as the interface shows it.
 */
export interface EngineStatus {
    /**
     * qBittorrent was found
     */
    "installed": boolean;
    "exe": string;
    "running": boolean;
    "version"?: string;
    "error"?: string;

    /**
     * InterfaceMissing: downloads are bound to an interface that's gone
     * (a VPN that disconnected), so nothing is sent or received.
     */
    "interfaceMissing": boolean;

    /**
     * downloads wait for the game to close
     */
    "gameRunning": boolean;
}

/**
 * FeedInfo is a feed as Settings shows it.
 */
export interface FeedInfo {
    "url": string;

    /**
     * from the feed; "" before its first good fetch
     */
    "name": string;
    "items": number;

    /**
     * items left out because they didn't pass the checks
     */
    "skipped": number;

    /**
     * unix seconds of the last good fetch
     */
    "fetched": number;
    "error"?: string;
    "etag"?: string;
    "enabled": boolean;
}

/**
 * InstallOptions are chosen before a game downloads.
 */
export interface InstallOptions {
    /**
     * the game's own folder; "" uses one in the games folder
     */
    "dir": string;

    /**
     * one of the offer's languages; "" for the installer's default
     */
    "language": string;

    /**
     * install once downloaded and checked; false only downloads
     */
    "install": boolean;
}

/**
 * MetaState is what the metadata worker is doing.
 */
export interface MetaState {
    "running": boolean;
    "done": number;
    "total": number;
}

/**
 * PadAction is one controller action.
 */
export interface PadAction {
    "action": string;
    "repeat": boolean;
}

/**
 * Profile is who's playing on this PC and how their playtime,
 * achievements and settings get to their other PCs, for the interface.
 */
export interface Profile {
    /**
     * Accounts are Syncer's; Enabled false when it has none, is off, or
     * is too old for them.
     */
    "enabled": boolean;
    "active"?: string;
    "accounts": syncer$0.Account[] | null;

    /**
     * Owner is whose playtime this PC adds to: the active account, the
     * last one this PC had, or "shared".
     */
    "owner": string;
    "ownerName"?: string;

    /**
     * Syncer: installed, answered, and has accounts.
     */
    "installed": boolean;
    "reachable": boolean;
    "supported": boolean;

    /**
     * Synced: Syncer syncs the profile folder (Backup: backs it up).
     */
    "synced": boolean;
    "backup": boolean;
    "dismissed": boolean;
    "dataError"?: string;
    "dir": string;

    /**
     * SettingsFrom is the PC the settings in use were saved on ("" this one).
     */
    "settingsFrom"?: string;
    "checkedAt"?: number;
}

/**
 * Saves is what Syncer knows about a game's saves, for the interface.
 */
export interface Saves {
    /**
     * Syncer is installed
     */
    "installed": boolean;

    /**
     * too old for the launcher API
     */
    "outdated": boolean;

    /**
     * Syncer answered
     */
    "available": boolean;
    "error"?: string;

    /**
     * Syncer has save folders for this game
     */
    "known": boolean;
    "folders": syncer$0.Folder[] | null;
}

/**
 * ScanState tells the frontend what the scanner is doing.
 */
export interface ScanState {
    "running": boolean;

    /**
     * unix seconds
     */
    "lastScan": number;
    "tookMs": number;
    "games": number;
    "added": number;

    /**
     * titles in the game database; 0 until it's downloaded
     */
    "known": number;
    "error"?: string;
}

/**
 * SessionAchievements are the achievements one session unlocked.
 */
export interface SessionAchievements {
    "gameId": number;
    "title": string;
    "unlocked": achievements$0.Achievement[] | null;
}

/**
 * StoreAccount is one store account as Settings shows it.
 */
export interface StoreAccount {
    "connected": boolean;

    /**
     * the store is on this PC (GOG: Galaxy's library)
     */
    "available": boolean;
    "name"?: string;
    "games": number;

    /**
     * unix seconds
     */
    "synced"?: number;
    "syncing": boolean;
    "error"?: string;
}

/**
 * StoreArt is a catalog game's metadata, for the store's pages.
 */
export interface StoreArt {
    "key": string;

    /**
     * nil: nothing was found
     */
    "meta": library$0.Meta | null;
}

/**
 * SyncerStatus is how Seaglass and Syncer get on, for Settings.
 */
export interface SyncerStatus {
    "installed": boolean;
    "version"?: string;

    /**
     * too old for the launcher API
     */
    "outdated": boolean;

    /**
     * Syncer answered
     */
    "connected": boolean;

    /**
     * its launcher API is up (it may not have been asked to start)
     */
    "running": boolean;
    "error"?: string;

    /**
     * its sync engine runs
     */
    "syncing": boolean;
    "paused": boolean;
    "pausedUntil"?: number;
    "backingUp": boolean;
    "lastBackup"?: number;
    "games": number;
    "conflicts": number;
    "checkedAt": number;
}

/**
 * UpdateState is what the interface shows about updates.
 */
export interface UpdateState {
    "current": string;
    "latest"?: string;
    "status": string;

    /**
     * 0 to 1 while downloading
     */
    "progress": number;
    "notes"?: string;
    "page": string;
    "error"?: string;

    /**
     * unix seconds
     */
    "checkedAt": number;

    /**
     * Failed: an install of Latest was started before but this is still
     * the old version, so it isn't retried on its own.
     */
    "failed": boolean;
}
