// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SavesService is the game's saves, through Syncer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * InstallSyncer installs Syncer, or updates it, from its latest release,
 * for this Windows account only (no administrator). Never over the same
 * or a newer version; see syncerInstallPlan for when it asks first. It
 * returns once the installer has exited; the interface shows it as
 * installing until then. Closing the installer isn't an error.
 */
export function InstallSyncer(): $CancellablePromise<void> {
    return $Call.ByID(2508183485);
}

/**
 * OpenSyncer shows Syncer's window.
 */
export function OpenSyncer(): $CancellablePromise<void> {
    return $Call.ByID(1792314974);
}

/**
 * Saves returns what Syncer knows about a game's saves. Syncer is started
 * in the background (without its window) when needed. Answers are kept
 * for a little while; fresh asks again right away.
 */
export function Saves(id: number, fresh: boolean): $CancellablePromise<$models.Saves> {
    return $Call.ByID(2707000040, id, fresh);
}

/**
 * Syncer reports Syncer's state. With start it starts Syncer (without its
 * window) when it isn't running, as a launch would; otherwise it only
 * looks, so opening Settings doesn't start anything.
 */
export function Syncer(start: boolean): $CancellablePromise<$models.SyncerStatus> {
    return $Call.ByID(3087953406, start);
}

/**
 * SyncerProject opens Syncer's home page.
 */
export function SyncerProject(): $CancellablePromise<void> {
    return $Call.ByID(3950654015);
}
