// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StoreService is the experimental store. Every method fails with
 * ErrStoreDisabled while the store is turned off.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../store/catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jobs$0 from "../store/jobs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as torrent$0 from "../torrent/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddDownload queues a magnet link or a link to a .torrent file. title
 * may be empty: the link's own name is used.
 */
export function AddDownload(source: string, title: string): $CancellablePromise<jobs$0.Job> {
    return $Call.ByID(324549332, source, title);
}

/**
 * AddFeed fetches a feed and adds it when Seaglass can read it.
 */
export function AddFeed(url: string): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1527192760, url);
}

/**
 * Addresses lists an interface's addresses.
 */
export function Addresses(iface: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2764782747, iface);
}

/**
 * Art returns the art and descriptions known for these catalog games and
 * looks up the rest, in this order (EventStoreArt brings them).
 */
export function Art(keys: string[] | null): $CancellablePromise<$models.StoreArt[] | null> {
    return $Call.ByID(1109411426, keys);
}

/**
 * Catalog returns a page of the catalog.
 */
export function Catalog(q: catalog$0.Query): $CancellablePromise<catalog$0.Page> {
    return $Call.ByID(3442553744, q);
}

/**
 * CatalogEntry returns one game in the catalog.
 */
export function CatalogEntry(key: string): $CancellablePromise<catalog$0.Entry> {
    return $Call.ByID(3533756356, key);
}

/**
 * CatalogLanguages lists the catalog's languages, most offered first.
 */
export function CatalogLanguages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4132144619);
}

/**
 * ChooseDownloadsFolder asks where downloads go.
 */
export function ChooseDownloadsFolder(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(3780776257);
}

/**
 * ChooseGamesFolder asks where games are installed.
 */
export function ChooseGamesFolder(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2838195199);
}

/**
 * ChooseInstallFolder asks for a game's folder (it isn't saved).
 */
export function ChooseInstallFolder(current: string): $CancellablePromise<string> {
    return $Call.ByID(1865893871, current);
}

/**
 * ChooseQBittorrent asks where qbittorrent.exe is.
 */
export function ChooseQBittorrent(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2172305544);
}

/**
 * DownloadAction pauses, resumes (or retries) or removes a download.
 * Removing deletes its downloaded files too when deleteFiles is set.
 */
export function DownloadAction(id: string, action: jobs$0.Action, deleteFiles: boolean): $CancellablePromise<void> {
    return $Call.ByID(2906851187, id, action, deleteFiles);
}

/**
 * DownloadOffer queues one of a game's offers (by its place in the
 * entry's offers).
 */
export function DownloadOffer(key: string, offer: number, opts: $models.InstallOptions): $CancellablePromise<jobs$0.Job> {
    return $Call.ByID(4276194449, key, offer, opts);
}

/**
 * Downloads returns the downloads, oldest first.
 */
export function Downloads(): $CancellablePromise<jobs$0.Job[] | null> {
    return $Call.ByID(2302684950);
}

/**
 * DownloadsFolder is where downloads go.
 */
export function DownloadsFolder(): $CancellablePromise<string> {
    return $Call.ByID(3111482918);
}

/**
 * Engine returns the download engine's status.
 */
export function Engine(): $CancellablePromise<$models.EngineStatus> {
    return $Call.ByID(2426923027);
}

/**
 * Feeds lists the catalog feeds and how their last fetch went.
 */
export function Feeds(): $CancellablePromise<$models.FeedInfo[] | null> {
    return $Call.ByID(340743898);
}

/**
 * GamesFolder is where games are installed.
 */
export function GamesFolder(): $CancellablePromise<string> {
    return $Call.ByID(1560198000);
}

/**
 * GetQBittorrent opens qBittorrent's download page.
 */
export function GetQBittorrent(): $CancellablePromise<void> {
    return $Call.ByID(3727889925);
}

/**
 * HasProxyPassword reports whether a proxy password is saved.
 */
export function HasProxyPassword(): $CancellablePromise<boolean> {
    return $Call.ByID(1740591640);
}

/**
 * InstallFolder suggests a folder for a game.
 */
export function InstallFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(3474141276, title);
}

/**
 * Interfaces lists the network interfaces downloads can be bound to.
 */
export function Interfaces(): $CancellablePromise<torrent$0.Interface[] | null> {
    return $Call.ByID(2450318113);
}

/**
 * RefreshFeeds fetches every enabled feed now.
 */
export function RefreshFeeds(): $CancellablePromise<$models.FeedInfo[] | null> {
    return $Call.ByID(3501220097);
}

/**
 * RemoveFeed removes a feed; its games leave the catalog.
 */
export function RemoveFeed(url: string): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(927034245, url);
}

/**
 * SetFeedEnabled shows a feed's games in the catalog, or not.
 */
export function SetFeedEnabled(url: string, on: boolean): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2158620060, url, on);
}

/**
 * SetProxyPassword stores the proxy's password encrypted for this Windows
 * account ("" removes it) and applies it.
 */
export function SetProxyPassword(password: string): $CancellablePromise<void> {
    return $Call.ByID(348886920, password);
}

/**
 * ShowDownload opens a download's folder in Explorer.
 */
export function ShowDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(2581068, id);
}

/**
 * StartEngine starts the download engine (to list network interfaces,
 * say) when it isn't running; it stops again when idle.
 */
export function StartEngine(): $CancellablePromise<$models.EngineStatus> {
    return $Call.ByID(2094697353);
}
