// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StoreService is the experimental store. Every method fails with
 * ErrStoreDisabled while the store is turned off.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../store/catalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "../store/discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as enrich$0 from "../store/enrich/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as jobs$0 from "../store/jobs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sources$0 from "../store/sources/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as torrent$0 from "../torrent/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcknowledgeWishlist marks a saved game's activity read ("" marks every
 * game's).
 */
export function AcknowledgeWishlist(key: string): $CancellablePromise<$models.WishlistItem[] | null> {
    return $Call.ByID(4020317092, key);
}

/**
 * AddDownload queues a magnet link or a link to a .torrent file. title
 * may be empty: the link's own name is used.
 */
export function AddDownload(source: string, title: string): $CancellablePromise<jobs$0.Job> {
    return $Call.ByID(324549332, source, title);
}

/**
 * AddFeed fetches a feed and adds it when Seaglass can read it.
 */
export function AddFeed(url: string): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1527192760, url);
}

/**
 * AddToWishlist saves a game. Its releases known now are the baseline:
 * only later ones become activity.
 */
export function AddToWishlist(key: string, title: string, steamAppID: number): $CancellablePromise<$models.WishlistItem[] | null> {
    return $Call.ByID(2922844770, key, title, steamAppID);
}

/**
 * Addresses lists an interface's addresses.
 */
export function Addresses(iface: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2764782747, iface);
}

/**
 * AllowDownload lets a download the safety checks blocked be installed
 * after all. confirm must be the download's title, typed by the person.
 */
export function AllowDownload(id: string, confirm: string): $CancellablePromise<void> {
    return $Call.ByID(1595628106, id, confirm);
}

/**
 * Art returns the art and descriptions known for these catalog games and
 * looks up the rest, in this order (EventStoreArt brings them).
 */
export function Art(keys: string[] | null): $CancellablePromise<$models.StoreArt[] | null> {
    return $Call.ByID(1109411426, keys);
}

/**
 * AttachReleaseTorrent validates user-selected metadata for an unresolved release.
 */
export function AttachReleaseTorrent(source: string, id: string): $CancellablePromise<sources$0.Entry> {
    return $Call.ByID(2977056769, source, id);
}

/**
 * AttachSourceTorrent asks for a .torrent file the person got in their
 * browser for an unresolved release and validates it.
 */
export function AttachSourceTorrent(key: string, releaseID: string): $CancellablePromise<discovery$0.PreparedRelease> {
    return $Call.ByID(3274921097, key, releaseID);
}

/**
 * BrowseGames answers a browse or search query from the index alone, at
 * once.
 */
export function BrowseGames(q: discovery$0.BrowseQuery): $CancellablePromise<discovery$0.SearchResult> {
    return $Call.ByID(3654478962, q);
}

/**
 * Catalog returns a page of the catalog.
 */
export function Catalog(q: catalog$0.Query): $CancellablePromise<catalog$0.Page> {
    return $Call.ByID(3442553744, q);
}

/**
 * CatalogEntry returns one game in the catalog.
 */
export function CatalogEntry(key: string): $CancellablePromise<catalog$0.Entry> {
    return $Call.ByID(3533756356, key);
}

/**
 * CatalogLanguages lists the catalog's languages, most offered first.
 */
export function CatalogLanguages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4132144619);
}

/**
 * ChooseDownloadsFolder asks where downloads go.
 */
export function ChooseDownloadsFolder(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(3780776257);
}

/**
 * ChooseGamesFolder asks where games are installed.
 */
export function ChooseGamesFolder(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2838195199);
}

/**
 * ChooseInstallFolder asks for a game's folder (it isn't saved).
 */
export function ChooseInstallFolder(current: string): $CancellablePromise<string> {
    return $Call.ByID(1865893871, current);
}

/**
 * ChooseQBittorrent asks where qbittorrent.exe is.
 */
export function ChooseQBittorrent(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2172305544);
}

/**
 * CompletionCandidates searches HowLongToBeat for title, so the person can
 * choose the right game.
 */
export function CompletionCandidates(key: string, title: string): $CancellablePromise<enrich$0.Candidate[] | null> {
    return $Call.ByID(1351683049, key, title);
}

/**
 * DiscoverReleases fetches metadata on demand; it never queues payload downloads.
 */
export function DiscoverReleases(source: string, query: string, resolve: boolean): $CancellablePromise<sources$0.Snapshot> {
    return $Call.ByID(2634802980, source, query, resolve);
}

/**
 * DiscoveryStatus says what discovery is doing.
 */
export function DiscoveryStatus(): $CancellablePromise<discovery$0.Status> {
    return $Call.ByID(2366554855);
}

/**
 * DownloadAction pauses, resumes (or retries) or removes a download.
 * Removing deletes its downloaded files too when deleteFiles is set.
 */
export function DownloadAction(id: string, action: jobs$0.Action, deleteFiles: boolean): $CancellablePromise<void> {
    return $Call.ByID(2906851187, id, action, deleteFiles);
}

export function DownloadLanguages(id: string): $CancellablePromise<$models.DownloadLanguageOptions> {
    return $Call.ByID(1080277804, id);
}

/**
 * DownloadOffer queues one of a game's offers (by its place in the
 * entry's offers).
 */
export function DownloadOffer(key: string, offer: number, opts: $models.InstallOptions): $CancellablePromise<jobs$0.Job> {
    return $Call.ByID(4276194449, key, offer, opts);
}

/**
 * DownloadRelease queues a prepared release's validated transport, after
 * the person confirmed it, through the same checks as DownloadOffer.
 */
export function DownloadRelease(key: string, releaseID: string, transport: number, opts: $models.InstallOptions): $CancellablePromise<jobs$0.Job> {
    return $Call.ByID(27636162, key, releaseID, transport, opts);
}

/**
 * Downloads returns the downloads, oldest first.
 */
export function Downloads(): $CancellablePromise<jobs$0.Job[] | null> {
    return $Call.ByID(2302684950);
}

/**
 * DownloadsFolder is where downloads go.
 */
export function DownloadsFolder(): $CancellablePromise<string> {
    return $Call.ByID(3111482918);
}

/**
 * Engine returns the download engine's status.
 */
export function Engine(): $CancellablePromise<$models.EngineStatus> {
    return $Call.ByID(2426923027);
}

/**
 * EnrichGames returns the cached enrichment for these games (cards on
 * screen, the first first) and fetches the rest; EventStoreEnrichment
 * brings them.
 */
export function EnrichGames(keys: string[] | null): $CancellablePromise<enrich$0.Enrichment[] | null> {
    return $Call.ByID(3788116099, keys);
}

/**
 * Feeds lists the catalog feeds and how their last fetch went.
 */
export function Feeds(): $CancellablePromise<$models.FeedInfo[] | null> {
    return $Call.ByID(340743898);
}

/**
 * GameDetails returns a game's page from the index and fetches missing
 * release details in the background (EventStoreGames brings them).
 */
export function GameDetails(key: string): $CancellablePromise<discovery$0.GameDetails> {
    return $Call.ByID(2861761367, key);
}

/**
 * GameEnrichment returns everything known about a game for its page,
 * fetching what is missing or old first (a few seconds at most).
 */
export function GameEnrichment(key: string): $CancellablePromise<enrich$0.Enrichment> {
    return $Call.ByID(2492157158, key);
}

/**
 * GameReviews returns one page of a game's Steam reviews.
 */
export function GameReviews(q: enrich$0.ReviewQuery): $CancellablePromise<enrich$0.ReviewPage> {
    return $Call.ByID(1340848476, q);
}

/**
 * GamesFolder is where games are installed.
 */
export function GamesFolder(): $CancellablePromise<string> {
    return $Call.ByID(1560198000);
}

/**
 * GetQBittorrent opens qBittorrent's download page.
 */
export function GetQBittorrent(): $CancellablePromise<void> {
    return $Call.ByID(3727889925);
}

/**
 * HasProxyPassword reports whether a proxy password is saved.
 */
export function HasProxyPassword(): $CancellablePromise<boolean> {
    return $Call.ByID(1740591640);
}

/**
 * HasVirusTotalKey reports whether a VirusTotal API key is saved.
 */
export function HasVirusTotalKey(): $CancellablePromise<boolean> {
    return $Call.ByID(3695390901);
}

/**
 * HoldDownloads pauses every download until resumed (the tray does the same).
 */
export function HoldDownloads(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(2973794121, on);
}

/**
 * InstallFolder suggests a folder for a game.
 */
export function InstallFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(3474141276, title);
}

/**
 * Interfaces lists the network interfaces downloads can be bound to.
 */
export function Interfaces(): $CancellablePromise<torrent$0.Interface[] | null> {
    return $Call.ByID(2450318113);
}

/**
 * OpenInSandbox opens Windows Sandbox with a download on its desktop,
 * read-only and without network, to try it there first.
 */
export function OpenInSandbox(id: string): $CancellablePromise<void> {
    return $Call.ByID(4121320589, id);
}

/**
 * OpenReleasePage hands an unresolved release to the person's browser.
 */
export function OpenReleasePage(source: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1444859129, source, id);
}

/**
 * OpenSourceRelease opens a release's article in the browser.
 */
export function OpenSourceRelease(key: string, releaseID: string): $CancellablePromise<void> {
    return $Call.ByID(3577528353, key, releaseID);
}

/**
 * PrepareRelease makes a release ready for the install confirmation: it
 * fetches the article when only its summary is known and tries the
 * supported torrent-metadata resolver once. Nothing is downloaded but
 * metadata.
 */
export function PrepareRelease(key: string, releaseID: string): $CancellablePromise<discovery$0.PreparedRelease> {
    return $Call.ByID(4259217065, key, releaseID);
}

/**
 * RefreshDiscovery fetches the newest listings of every chosen source now.
 */
export function RefreshDiscovery(): $CancellablePromise<discovery$0.Status> {
    return $Call.ByID(2968838102);
}

/**
 * RefreshFeeds fetches every enabled feed now.
 */
export function RefreshFeeds(): $CancellablePromise<$models.FeedInfo[] | null> {
    return $Call.ByID(3501220097);
}

/**
 * RemoveFeed removes a feed; its games leave the catalog.
 */
export function RemoveFeed(url: string): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(927034245, url);
}

/**
 * RemoveFromWishlist forgets a saved game and its activity.
 */
export function RemoveFromWishlist(key: string): $CancellablePromise<$models.WishlistItem[] | null> {
    return $Call.ByID(437754034, key);
}

/**
 * ReviewRelease adds only a resolved, explicitly reviewed offer to the catalog.
 */
export function ReviewRelease(source: string, id: string, transport: number): $CancellablePromise<string> {
    return $Call.ByID(2612472346, source, id, transport);
}

/**
 * SandboxAvailable reports whether Windows Sandbox is turned on.
 */
export function SandboxAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(3185661807);
}

/**
 * SearchGames searches the chosen source sites and Steam for q.Text to
 * fill gaps in the index, then answers like BrowseGames. A newer call
 * cancels an older one, which then returns its partial result.
 */
export function SearchGames(q: discovery$0.BrowseQuery): $CancellablePromise<discovery$0.SearchResult> {
    return $Call.ByID(836849064, q);
}

/**
 * SetCompletionMatch makes hltbID the game's HowLongToBeat match, kept
 * across refreshes (0 goes back to the automatic match).
 */
export function SetCompletionMatch(key: string, hltbID: number): $CancellablePromise<enrich$0.Enrichment> {
    return $Call.ByID(3699193174, key, hltbID);
}

/**
 * SetDownloadLanguages changes known optional packs and keeps manual installation
 * selected, so newly requested files can finish and be checked first.
 */
export function SetDownloadLanguages(id: string, language: string, setupLanguage: string, ask: boolean): $CancellablePromise<jobs$0.Job> {
    return $Call.ByID(3284740262, id, language, setupLanguage, ask);
}

/**
 * SetFeedEnabled shows a feed's games in the catalog, or not.
 */
export function SetFeedEnabled(url: string, on: boolean): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2158620060, url, on);
}

/**
 * SetProxyPassword stores the proxy's password encrypted for this Windows
 * account ("" removes it) and applies it.
 */
export function SetProxyPassword(password: string): $CancellablePromise<void> {
    return $Call.ByID(348886920, password);
}

/**
 * SetSteamMatch corrects which Steam game a game's releases are (appID 0:
 * not on Steam). The correction survives refreshes. The game's key can
 * change; the returned details carry the new one.
 */
export function SetSteamMatch(key: string, appID: number, name: string): $CancellablePromise<discovery$0.GameDetails> {
    return $Call.ByID(3816352282, key, appID, name);
}

/**
 * SetVirusTotalKey stores the person's VirusTotal API key encrypted for
 * this Windows account ("" removes it). Only file hashes are looked up.
 */
export function SetVirusTotalKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(3842706853, key);
}

/**
 * SetupSources records the one-time source choice (or a later change in
 * Settings) and starts indexing the chosen sources at once.
 */
export function SetupSources(chosen: string[] | null): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2194619824, chosen);
}

/**
 * ShowDownload opens a download's folder in Explorer.
 */
export function ShowDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(2581068, id);
}

/**
 * StartEngine starts the download engine (to list network interfaces,
 * say) when it isn't running; it stops again when idle.
 */
export function StartEngine(): $CancellablePromise<$models.EngineStatus> {
    return $Call.ByID(2094697353);
}

/**
 * StoreHome returns the Store's front page from the index.
 */
export function StoreHome(): $CancellablePromise<discovery$0.Home> {
    return $Call.ByID(1545618969);
}

/**
 * Updates lists the games the store installed that have a newer version.
 */
export function Updates(): $CancellablePromise<catalog$0.Entry[] | null> {
    return $Call.ByID(4210487325);
}

/**
 * Wishlist lists the saved games, newest first.
 */
export function Wishlist(): $CancellablePromise<$models.WishlistItem[] | null> {
    return $Call.ByID(2412536106);
}
