// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Kind is a controller family, for the button glyphs.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlayStation = "playstation",
    Xbox = "xbox",
    Nintendo = "nintendo",
    Other = "other",
};

/**
 * Raw is the whole state of the controller in use: which SDL gamepad
 * buttons are down (bit n is button n) and its axes (left stick x, y,
 * right stick x, y, left and right trigger; -32768 to 32767, triggers
 * from 0).
 */
export interface Raw {
    "buttons": number;
    "axes": number[];
}

/**
 * State describes the controller in use.
 */
export interface State {
    "connected": boolean;
    "name": string;
    "kind": Kind;
    "dualSense": boolean;

    /**
     * percent, -1 unknown
     */
    "battery": number;
    "wireless": boolean;
    "error"?: string;

    /**
     * Slow: Windows took seconds to answer SDL about the controllers.
     * A controller can get into a state where every question to it waits
     * for a timeout; reconnecting it ends that.
     */
    "slow"?: boolean;
}
