// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as app$0 from "../../../../ApolloF/Seaglass/internal/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as launch$0 from "../../../../ApolloF/Seaglass/internal/launch/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as library$0 from "../../../../ApolloF/Seaglass/internal/library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as pad$0 from "../../../../ApolloF/Seaglass/internal/pad/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as settings$0 from "../../../../ApolloF/Seaglass/internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as jobs$0 from "../../../../ApolloF/Seaglass/internal/store/jobs/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "accounts:changed": app$0.Accounts;
            "achievements:session": app$0.SessionAchievements;
            "games:updated": library$0.Game[] | null;
            "launch:session": launch$0.Session;
            "library:changed": string;
            "meta:state": app$0.MetaState;
            "overlay:action": app$0.PadAction;
            "pad:action": app$0.PadAction;
            "pad:raw": pad$0.Raw;
            "pad:state": pad$0.State;
            "profile:changed": app$0.Profile;
            "scan:state": app$0.ScanState;
            "settings:changed": settings$0.Settings;
            "store:catalog": number;
            "store:engine": app$0.EngineStatus;
            "store:jobs": jobs$0.Job[] | null;
            "ui:mode": string;
            "update:state": app$0.UpdateState;
        }
    }
}
