// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Candidate is one HowLongToBeat search result the person can choose.
 */
export interface Candidate {
    "hltbId": number;
    "title": string;
    "year": number;
    "main": number;
    "mainExtras": number;
    "completionist": number;
    "url": string;
}

/**
 * Completion is a game's HowLongToBeat times, in minutes; 0 is unknown.
 */
export interface Completion {
    /**
     * 0: no confident match
     */
    "hltbId": number;
    "title"?: string;
    "main": number;
    "mainExtras": number;
    "completionist": number;

    /**
     * the game's page, or a search on HowLongToBeat
     */
    "url": string;

    /**
     * Corrected: the person chose this match.
     */
    "corrected": boolean;
    "fetchedAt": number;
    "state": string;
    "error"?: string;
}

/**
 * Critic is the Metacritic score and link Steam's game metadata gives.
 * Seaglass doesn't fetch critic articles.
 */
export interface Critic {
    "appId": number;

    /**
     * 0: Steam gives none
     */
    "score": number;
    "url"?: string;
    "fetchedAt": number;
    "state": string;
    "error"?: string;
}

/**
 * Enrichment is everything known about one game, for its page and cards.
 */
export interface Enrichment {
    /**
     * the game's discovery key
     */
    "key": string;
    "steamAppId": number;
    "reviews": ReviewSummary;
    "critic": Critic;
    "completion": Completion;

    /**
     * PopularRank is the game's place on the chart; 0 off the chart or unknown.
     */
    "popularRank": number;
}

/**
 * Review is one Steam user review, shown as plain text with its link.
 */
export interface Review {
    /**
     * Steam's recommendation id
     */
    "id": string;

    /**
     * persona name when given, else the SteamID
     */
    "author": string;
    "recommended": boolean;

    /**
     * plain text; never rendered as HTML
     */
    "text": string;
    "language"?: string;
    "helpful": number;
    "funny": number;

    /**
     * Playtime in minutes; 0 when Steam doesn't say.
     */
    "playtimeAtReview": number;
    "playtimeForever": number;
    "posted": number;

    /**
     * the review on Steam
     */
    "url": string;
}

/**
 * ReviewPage is one page of reviews.
 */
export interface ReviewPage {
    "appId": number;
    "reviews": Review[] | null;

    /**
     * for the next page
     */
    "cursor": string;
    "more": boolean;
    "state": string;
    "error"?: string;
}

/**
 * ReviewQuery asks for one page of reviews.
 */
export interface ReviewQuery {
    "appId": number;

    /**
     * "" or "*" for the first page; then ReviewPage.Cursor
     */
    "cursor": string;

    /**
     * ReviewsHelpful or ReviewsRecent
     */
    "filter": string;

    /**
     * Steam language name ("english"); "" all
     */
    "language": string;
}

/**
 * ReviewSummary is a game's Steam review scores.
 */
export interface ReviewSummary {
    "appId": number;
    "overall": Score;

    /**
     * the last 30 days; Total 0 when Steam gives none
     */
    "recent": Score;

    /**
     * the game's reviews on Steam
     */
    "url": string;
    "fetchedAt": number;
    "state": string;
    "error"?: string;
}

/**
 * Score is one Steam review summary.
 */
export interface Score {
    /**
     * Steam's own words: "Very Positive"
     */
    "label"?: string;

    /**
     * positive share 0..100
     */
    "percent": number;

    /**
     * 0: no reviews (Label says so) or unknown
     */
    "total": number;
}
