// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityView is an Activity for the interface (times in unix seconds).
 */
export interface ActivityView {
    "id": string;
    "kind": string;
    "releaseId": string;
    "source": string;
    "sourceName": string;
    "version"?: string;
    "at": number;
    "read": boolean;
}
