// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Interface is a network interface the client can bind to.
 */
export interface Interface {
    /**
     * the client's id for it
     */
    "id": string;

    /**
     * as Windows names it ("Ethernet", "Wi-Fi", a VPN adapter)
     */
    "name": string;
}

/**
 * Network is how the client connects. The zero value isn't useful; start
 * from DefaultNetwork.
 */
export interface Network {
    /**
     * Interface binds all traffic to one network interface (a VPN adapter,
     * say), by the client's id for it; "" uses any. While a bound
     * interface is missing, nothing is sent or received at all.
     */
    "interface": string;

    /**
     * one address of Interface; "" uses all of them
     */
    "address": string;

    /**
     * incoming connections; 0 picks a random one at each start
     */
    "port": number;

    /**
     * forward Port on the router with UPnP / NAT-PMP
     */
    "upnp": boolean;

    /**
     * none, socks5, http
     */
    "proxy": string;
    "proxyHost": string;
    "proxyPort": number;

    /**
     * "" for none; the password is kept encrypted, apart
     */
    "proxyUser": string;

    /**
     * peer connections go through the proxy too, not only trackers
     */
    "proxyPeers": boolean;

    /**
     * prefer, require, off
     */
    "encryption": string;

    /**
     * find peers without trackers
     */
    "dht": boolean;

    /**
     * peers tell each other about peers
     */
    "pex": boolean;

    /**
     * find peers on the local network
     */
    "lsd": boolean;

    /**
     * don't tell peers and trackers which client this is
     */
    "anonymous": boolean;

    /**
     * KiB/s; 0 for no limit
     */
    "downLimit": number;

    /**
     * KiB/s; 0 for no limit
     */
    "upLimit": number;

    /**
     * downloads at once
     */
    "maxActive": number;

    /**
     * stop seeding at this upload/download ratio; 0 stops when complete, -1 never
     */
    "seedRatio": number;
}

/**
 * State is where a torrent is, as Seaglass tells them apart.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * waiting for a free download slot
     */
    Queued = "queued",

    /**
     * fetching the torrent's file list from peers
     */
    Metadata = "metadata",

    /**
     * receiving data (or trying to: stalled counts too)
     */
    Downloading = "downloading",

    /**
     * stopped before it was complete
     */
    Paused = "paused",

    /**
     * verifying pieces already on disk
     */
    Checking = "checking",

    /**
     * complete, uploading to others
     */
    Seeding = "seeding",

    /**
     * complete and stopped
     */
    Complete = "complete",

    /**
     * the client gave up (disk error, missing files)
     */
    Failed = "failed",
};
