// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Finding is one check's result.
 */
export interface Finding {
    /**
     * integrity, signature, files, defender, virustotal
     */
    "check": string;
    "level": Level;
    "text": string;
}

/**
 * Level is how much a finding matters.
 */
export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * a check passed
     */
    OK = "ok",

    /**
     * worth knowing, not a problem
     */
    Info = "info",

    /**
     * the person decides
     */
    Warn = "warn",

    /**
     * not installed unless the person insists
     */
    Block = "block",
};

/**
 * Report is everything the checks found.
 */
export interface Report {
    "payloadSkipped"?: boolean;
    "verdict": Verdict;
    "findings": Finding[] | null;

    /**
     * the installer (or game exe), relative to the download
     */
    "main"?: string;
    "sha256"?: string;

    /**
     * unix seconds
     */
    "checked": number;

    /**
     * the person chose to install it anyway
     */
    "overridden"?: boolean;
}

/**
 * Verdict is what a report comes to.
 */
export enum Verdict {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Clean = "clean",
    Caution = "warn",
    Blocked = "block",
};
