// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as torrent$0 from "../torrent/models.js";

/**
 * FeedSource is a catalog feed the person added.
 */
export interface FeedSource {
    "url": string;
    "enabled": boolean;
}

/**
 * Settings are the user's preferences. New fields get their default when
 * an older settings file doesn't have them.
 */
export interface Settings {
    /**
     * Library
     * extra folders whose subfolders are games
     */
    "folders": string[] | null;

    /**
     * also look in common game folders on every drive
     */
    "autoFolders": boolean;

    /**
     * recognise games on Steam API emulators and from repacks
     */
    "detectExternal": boolean;

    /**
     * keep low-confidence matches in New on this PC for a check
     */
    "reviewUncertain": boolean;

    /**
     * list games that aren't installed (anymore)
     */
    "showNotInstalled": boolean;

    /**
     * list games connected store accounts own but aren't installed
     */
    "showOwned": boolean;

    /**
     * read GOG Galaxy's library for owned games
     */
    "ownedGOG": boolean;

    /**
     * libraries whose games aren't shown (steam, epic, …, external, folder)
     */
    "hiddenSources": string[] | null;

    /**
     * Appearance
     * system, dark, light (desktop mode)
     */
    "theme": string;

    /**
     * deck, console, orbit
     */
    "bigPictureLayout": string;

    /**
     * Big picture and controller
     */
    "openBigPictureOnController": boolean;
    "startInBigPicture": boolean;
    "sounds": boolean;
    "haptics": boolean;
    "lightbar": boolean;
    "psButton": boolean;

    /**
     * auto, playstation, xbox
     */
    "glyphs": string;

    /**
     * While playing
     * close the interface while a game runs (frees its memory)
     */
    "closeWhilePlaying": boolean;

    /**
     * listen (PS button opens the overlay), off (release the controller)
     */
    "padWhilePlaying": string;

    /**
     * follow games started outside Seaglass (playtime, controller)
     */
    "noticeExternal": boolean;

    /**
     * Saves, through Syncer
     * sync a game's saves before it starts
     */
    "syncSavesBefore": boolean;

    /**
     * back its saves up after it exits
     */
    "backupSavesAfter": boolean;

    /**
     * seconds to wait for a sync before playing
     */
    "syncWait": number;

    /**
     * start Syncer (without its window) when it isn't running
     */
    "startSyncer": boolean;

    /**
     * Syncer syncs playtime, achievements and settings between PCs
     */
    "syncProfile": boolean;

    /**
     * take the settings saved last on another PC (see Portable)
     */
    "sameSettings": boolean;

    /**
     * with several Syncer accounts, ask who's playing before a game starts
     */
    "askWhoPlays": boolean;

    /**
     * Achievements
     * show achievements (read from stores and emulator files)
     */
    "achievements": boolean;

    /**
     * show hidden achievements before they're unlocked (spoilers)
     */
    "showHiddenAchievements": boolean;

    /**
     * Updates
     * check GitHub for new versions and install them on the next start or while idle in the tray
     */
    "autoUpdate": boolean;

    /**
     * Experimental. Not portable: what this PC downloads, and how, is its own.
     * the store: catalogs from feeds the user adds, downloads and installs
     */
    "experimentalStore": boolean;
    "store": StoreSettings;

    /**
     * Welcomed: the first-start welcome was seen (or skipped).
     */
    "welcomed": boolean;
}

/**
 * StoreSettings are the experimental store's.
 */
export interface StoreSettings {
    /**
     * qbittorrent.exe; "" uses the installed one
     */
    "qbittorrent": string;

    /**
     * where downloads go; "" is Downloads\Seaglass in the user's folder
     */
    "downloads": string;

    /**
     * where games are installed; "" is Games in the user's folder
     */
    "games": string;

    /**
     * keep a download (and seed it) after its game is installed
     */
    "keepDownloads": boolean;

    /**
     * downloads wait while a game runs
     */
    "pauseWhilePlaying": boolean;
    "network": torrent$0.Network;

    /**
     * catalogs, in the order they were added
     */
    "feeds": FeedSource[] | null;
}
