// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Entry {
    "id": string;
    "sourceId": string;
    "pageUrl": string;
    "documentSha256": string;
    "rawTitle": string;
    "title": string;
    "titleKey": string;
    "version"?: string;
    "publishedAt"?: string | null;
    "updatedAt"?: string | null;
    "sizeBytes"?: number;
    "sizeIsMinimum"?: boolean;
    "sizeClaim"?: string;
    "sizeOptionsBytes"?: number[] | null;
    "installedSizeBytes"?: number;
    "languageClaim"?: string;
    "releaseKind": string;
    "transports": Transport[] | null;
    "references": Reference[] | null;
    "needsReview": boolean;
    "summaryOnly"?: boolean;
    "warnings": string[] | null;
}

export interface Evidence {
    "url": string;
    "sha256": string;
    "bytes": number;
    "entries": number;
}

export interface Group {
    "titleKey": string;
    "title": string;
    "entryIds": string[] | null;
    "needsReview": boolean;
}

export interface Reference {
    "url": string;
    "label": string;
    "kind"?: string;
    "state"?: string;
    "reason"?: string;
}

export interface Snapshot {
    "schema": string;
    "source": Source;
    "collectedAt": string;
    "documentSha256": string;
    "entries": Entry[] | null;
    "groups": Group[] | null;
    "documents"?: Evidence[] | null;
    "warnings"?: string[] | null;
}

export interface Source {
    "id": string;
    "name": string;
    "host": string;
    "startUrl": string;
}

export interface Transport {
    "kind": string;
    "uri": string;
    "infoHash"?: string;
    "torrentName"?: string;
    "sizeBytes"?: number;
    "metadataSha256"?: string;
}
