// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is one game in the catalog.
 */
export interface Entry {
    /**
     * "steam:<id>" or "title:<normalized title>"
     */
    "key": string;
    "title": string;
    "steamAppId"?: number;

    /**
     * newest version first
     */
    "offers": Offer[] | null;

    /**
     * the newest offer's
     */
    "version": string;

    /**
     * the newest build date, YYYY-MM-DD
     */
    "updated": string;

    /**
     * the newest offer's download
     */
    "size": number;

    /**
     * of every offer together
     */
    "languages": string[] | null;

    /**
     * Filled in for the interface when the entry is asked for.
     */
    "recommended"?: Recommendation | null;
    "installed"?: Installed | null;
}

/**
 * Installed is a catalog game the store installed.
 */
export interface Installed {
    /**
     * the download (job) that installed it
     */
    "download": string;
    "version": string;
    "dir": string;

    /**
     * the catalog has a newer version
     */
    "update": boolean;
}

/**
 * Offer is one downloadable version of a game, from one feed.
 */
export interface Offer {
    "title": string;
    "version"?: string;

    /**
     * YYYY-MM-DD
     */
    "buildDate"?: string;

    /**
     * the download
     */
    "sizeBytes"?: number;
    "installedSizeBytes"?: number;

    /**
     * a magnet link, or…
     */
    "magnet"?: string;

    /**
     * …the URL of a .torrent file
     */
    "torrentUrl"?: string;
    "languages"?: string[] | null;

    /**
     * windows
     */
    "platform"?: string;

    /**
     * inno, nsis, msi, archive, portable
     */
    "installerType"?: string;

    /**
     * of the installer, checked after downloading
     */
    "sha256"?: string;

    /**
     * for art and descriptions
     */
    "steamAppId"?: number;
    "notes"?: string;
    "feedUrl": string;
    "feedName": string;
}

/**
 * Page is one page of entries.
 */
export interface Page {
    "entries": Entry[] | null;

    /**
     * matching entries, on every page together
     */
    "total": number;
}

/**
 * Query picks and orders entries.
 */
export interface Query {
    "text": string;

    /**
     * "" for any
     */
    "language": string;

    /**
     * title, updated, size
     */
    "sort": string;
    "offset": number;

    /**
     * at most 200
     */
    "limit": number;
}

/**
 * Recommendation is the offer to get, and why.
 */
export interface Recommendation {
    /**
     * index into Entry.Offers
     */
    "offer": number;
    "why": string[] | null;
}
