// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as safety$0 from "../../safety/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as torrent$0 from "../../torrent/models.js";

/**
 * Action is something the person asks of a download.
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Pause = "pause",

    /**
     * also retries a failed download or install
     */
    Resume = "resume",

    /**
     * forgets the download (an installed game stays)
     */
    Remove = "remove",

    /**
     * installs a checked download
     */
    Install = "install",

    /**
     * installs a blocked download anyway (after confirming)
     */
    Allow = "allow",

    /**
     * runs the game's uninstaller
     */
    Uninstall = "uninstall",

    /**
     * runs the safety checks again
     */
    Recheck = "recheck",
};

/**
 * Job is one download.
 */
export interface Job {
    /**
     * also the engine's tag for its torrent
     */
    "id": string;
    "title": string;

    /**
     * magnet link or .torrent URL
     */
    "source": string;
    "savePath": string;

    /**
     * From the catalog (empty for a link the person pasted).
     */
    "gameKey"?: string;
    "version"?: string;
    "feedName"?: string;

    /**
     * How to install it, chosen before downloading.
     * the game's own folder
     */
    "installDir"?: string;

    /**
     * as the feed names it; "" for the installer's default
     */
    "language"?: string;

    /**
     * install as soon as it's downloaded and checked
     */
    "autoInstall"?: boolean;

    /**
     * the installer's, from the feed
     */
    "sha256"?: string;

    /**
     * the installed download this one updates, in its folder
     */
    "replaces"?: string;

    /**
     * After downloading.
     */
    "safety"?: safety$0.Report | null;

    /**
     * the kind of installer found: inno, nsis, msi, archive, portable
     */
    "installer"?: string;

    /**
     * command line that removes the game
     */
    "uninstaller"?: string;
    "installedAt"?: number;

    /**
     * bytes in the game's folder while installing
     */
    "installDone"?: number;

    /**
     * the installer has done nothing visible for a while
     */
    "stalled"?: boolean;

    /**
     * once the engine has it
     */
    "hash"?: string;

    /**
     * the torrent's own name: its folder (or file) in SavePath
     */
    "name"?: string;
    "state": State;
    "error"?: string;

    /**
     * Progress, from the engine.
     */
    "engine"?: torrent$0.State;
    "size": number;
    "done": number;
    "downSpeed": number;
    "upSpeed": number;
    "seeds": number;
    "peers": number;
    "eta": number;
    "seeding": boolean;

    /**
     * unix seconds
     */
    "created": number;
    "finished"?: number;
}

/**
 * State is where a download is.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * waiting to be handed to the engine
     */
    Queued = "queued",

    /**
     * in the engine and wanted
     */
    Downloading = "downloading",

    /**
     * paused by the person
     */
    Paused = "paused",

    /**
     * downloaded; the safety checks run
     */
    Scanning = "scanning",

    /**
     * downloaded and checked: ready to install
     */
    Downloaded = "downloaded",

    /**
     * the safety checks found a problem
     */
    Blocked = "blocked",

    /**
     * the installer runs
     */
    Installing = "installing",

    /**
     * the game is installed and in the library
     */
    Installed = "installed",

    /**
     * stopped with an error; can be retried
     */
    Failed = "failed",
};
