// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as torrent$0 from "../../torrent/models.js";

/**
 * Action is something the person asks of a download.
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Pause = "pause",

    /**
     * also retries a failed download
     */
    Resume = "resume",
    Remove = "remove",
};

/**
 * Job is one download.
 */
export interface Job {
    /**
     * also the engine's tag for its torrent
     */
    "id": string;
    "title": string;

    /**
     * magnet link or .torrent URL
     */
    "source": string;
    "savePath": string;

    /**
     * once the engine has it
     */
    "hash"?: string;

    /**
     * the torrent's own name: its folder (or file) in SavePath
     */
    "name"?: string;
    "state": State;
    "error"?: string;

    /**
     * Progress, from the engine.
     */
    "engine"?: torrent$0.State;
    "size": number;
    "done": number;
    "downSpeed": number;
    "upSpeed": number;
    "seeds": number;
    "peers": number;
    "eta": number;
    "seeding": boolean;

    /**
     * unix seconds
     */
    "created": number;
    "finished"?: number;
}

/**
 * State is where a download is.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * waiting to be handed to the engine
     */
    Queued = "queued",

    /**
     * in the engine and wanted
     */
    Downloading = "downloading",

    /**
     * paused by the person
     */
    Paused = "paused",

    /**
     * every wanted file is on disk
     */
    Downloaded = "downloaded",

    /**
     * stopped with an error; can be retried
     */
    Failed = "failed",
};
