// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowsePage is one page of source-backed games.
 */
export interface BrowsePage {
    "games": GameSummary[] | null;

    /**
     * matching games on every page together
     */
    "total": number;

    /**
     * Unknown counts games left out only because the filtered field
     * (language or genre) is unknown for them, so the interface can say so
     * instead of inventing a value.
     */
    "unknown": number;

    /**
     * filter choices, most common first
     */
    "languages": string[] | null;
    "genres": string[] | null;
}

/**
 * BrowseQuery picks and orders games.
 */
export interface BrowseQuery {
    "text": string;

    /**
     * fitgirl, dodi, feeds; empty: all
     */
    "sources": string[] | null;

    /**
     * "" any
     */
    "language": string;

    /**
     * "" any
     */
    "genre": string;

    /**
     * Availability: "" any, "installable", "unresolved" (no validated
     * transport yet).
     */
    "availability": string;

    /**
     * "" any, "installed", "not-installed"
     */
    "installed": string;

    /**
     * Sort: title, published (newest first), popular (chart order, unranked
     * last), reviews (best first, unknown last).
     */
    "sort": string;
    "offset": number;

    /**
     * 60 by default, at most 200
     */
    "limit": number;
}

/**
 * Change says which games changed, so open pages reload.
 */
export interface Change {
    /**
     * these games changed
     */
    "keys": string[] | null;

    /**
     * the whole index changed (refresh, setting)
     */
    "all": boolean;
}

/**
 * GameDetails is a game's page.
 */
export interface GameDetails {
    "summary": GameSummary;

    /**
     * newest publication first
     */
    "releases": Release[] | null;

    /**
     * Recommended is the index in Releases to offer first; -1 none.
     */
    "recommended": number;
    "why": string[] | null;
    "identity": Identity;

    /**
     * Loading: release details are being fetched; EventStoreGames brings
     * the update.
     */
    "loading": boolean;
}

/**
 * GameSummary is one game on a shelf, in Browse or in search results.
 */
export interface GameSummary {
    /**
     * "steam:<appid>" or "title:<normalized title>", as catalog.Entry.Key
     */
    "key": string;
    "title": string;
    "steamAppId"?: number;

    /**
     * SourceBacked: at least one source release or feed offer exists.
     * Steam-only search results have none and cannot be installed.
     */
    "sourceBacked": boolean;

    /**
     * fitgirl, dodi, feeds
     */
    "sources": string[] | null;
    "releases": number;

    /**
     * the newest release's claim, as published
     */
    "version"?: string;

    /**
     * PublishedAt is the newest source publication; UpdatedAt the newest
     * change to a source release. Neither is a game release or build date.
     */
    "publishedAt": number;
    "updatedAt": number;

    /**
     * ReleaseDate is the game's own release date as Steam's metadata
     * gives it ("12 Mar, 2024"); "" unknown. Never a source date.
     */
    "releaseDate"?: string;

    /**
     * the newest release's download claim; 0 unknown
     */
    "sizeBytes": number;

    /**
     * claimed by any release; empty: unknown
     */
    "languages": string[] | null;

    /**
     * from Steam once its metadata is known; empty: unknown
     */
    "genres": string[] | null;
    "installable": boolean;

    /**
     * BrowserOnly: every source release opens in a browser (the source
     * offers no torrents). Announced: the sources only announce the game.
     */
    "browserOnly": boolean;
    "announced": boolean;

    /**
     * PopularRank is the place on Steam's most-played chart (1 = first); 0
     * when it isn't on the chart or the chart is unavailable. Never derived
     * from anything else.
     */
    "popularRank": number;

    /**
     * Steam's overall review summary, once fetched for this game.
     * positive share 0..100
     */
    "reviewPercent": number;

    /**
     * 0: unknown or no reviews
     */
    "reviewTotal": number;
    "reviewLabel"?: string;

    /**
     * CompletionMain is HowLongToBeat's Main Story time in minutes from
     * the cache; 0 unknown. Cards never fetch it.
     */
    "completionMain": number;
    "installed"?: Installed | null;
    "wishlisted": boolean;

    /**
     * Activity: unread wishlist activity (a first release or a confirmed
     * newer version).
     */
    "activity": boolean;
}

/**
 * Home is the Store's front page.
 */
export interface Home {
    /**
     * newest source publication first
     */
    "new": GameSummary[] | null;

    /**
     * Steam chart order among source-backed games
     */
    "popular": GameSummary[] | null;

    /**
     * PopularState: StateOK, StateStale (cached chart) or StateUnavailable
     * (no chart: the shelf shows its empty state, never another ranking).
     */
    "popularState": string;

    /**
     * source releases that changed, newest change first
     */
    "updated": GameSummary[] | null;

    /**
     * wishlisted games with unread activity
     */
    "wishlist": GameSummary[] | null;

    /**
     * Featured are a few source-backed games for the top of the page:
     * new and popular first, never installed ones.
     */
    "featured": GameSummary[] | null;

    /**
     * Recommended are source-backed games that share genres with games
     * played recently or wishlisted, never installed ones; with no useful
     * history they are popular games. RecommendedBasis says which.
     */
    "recommended": Recommendation[] | null;

    /**
     * Basis* constants
     */
    "recommendedBasis": string;
    "status": Status;
}

/**
 * Identity says how a game's Steam match was made.
 */
export interface Identity {
    "steamAppId": number;
    "name"?: string;

    /**
     * How: "game-database" (Seaglass's identification), "correction" (the
     * person chose it), "feed" (the feed gave it) or "" (no Steam match).
     */
    "how": string;
    "corrected": boolean;
}

/**
 * Installed is a game the Store installed on this PC.
 */
export interface Installed {
    "download": string;
    "version": string;

    /**
     * a release is a confirmed newer version
     */
    "update": boolean;
}

/**
 * InstalledCopy is where the Store installed a game, and which version.
 */
export interface InstalledCopy {
    "version": string;
    "dir": string;
}

/**
 * PreparedOffer is one validated way to download a prepared release.
 */
export interface PreparedOffer {
    /**
     * index for DownloadRelease
     */
    "transport": number;
    "title": string;
    "version"?: string;
    "sizeBytes": number;
    "installedSizeBytes"?: number;
    "languages": string[] | null;
    "torrentName"?: string;
    "infoHash": string;
    "sourceName": string;
}

/**
 * PreparedRelease is a release made ready for the install confirmation.
 */
export interface PreparedRelease {
    "gameKey": string;
    "release": Release;

    /**
     * Ready: a validated transport exists; Offers is filled and
     * DownloadRelease can queue one of them.
     */
    "ready": boolean;

    /**
     * Offers are the release as the install confirmation shows it, one per
     * validated transport.
     */
    "offers": PreparedOffer[] | null;

    /**
     * State: "ready", "unresolved" (resolution failed or needs a browser),
     * "update-only", "unavailable", "preview" (announced, nothing to
     * download yet), "browser" (a source without torrents).
     */
    "state": string;
    "reason"?: string;
    "warnings": string[] | null;

    /**
     * Installed is the copy the Store installed, which an update replaces
     * in its folder; nil when there is none.
     */
    "installed"?: InstalledCopy | null;
}

/**
 * ProviderProgress is one remote search: a source site or Steam.
 */
export interface ProviderProgress {
    /**
     * fitgirl, dodi, steam
     */
    "id": string;
    "name": string;

    /**
     * State* constants
     */
    "state": string;

    /**
     * results it returned
     */
    "found": number;
    "error"?: string;

    /**
     * Cached: answered from the one-hour search cache.
     */
    "cached": boolean;
}

/**
 * Recommendation is one recommended game and why.
 */
export interface Recommendation {
    "game": GameSummary;

    /**
     * Because names the played or wishlisted games it shares genres with,
     * most relevant first, at most three; empty for BasisPopular.
     */
    "because": string[] | null;

    /**
     * the shared genres
     */
    "genres": string[] | null;
}

/**
 * Release is one release choice on a game's page.
 */
export interface Release {
    /**
     * sources.Entry.ID, or "feed:<offer index>"
     */
    "id": string;

    /**
     * OriginSource or OriginFeed
     */
    "origin": string;

    /**
     * fitgirl, dodi, or the feed's URL
     */
    "source": string;
    "sourceName": string;
    "title": string;
    "rawTitle": string;
    "version"?: string;
    "pageUrl"?: string;

    /**
     * PublishedAt / UpdatedAt are the source's publication and change
     * times, not the game's release or build date.
     */
    "publishedAt": number;
    "updatedAt": number;
    "sizeBytes": number;
    "sizeClaim"?: string;
    "sizeIsMinimum"?: boolean;
    "installedSizeBytes"?: number;

    /**
     * recognized names; empty: unknown
     */
    "languages": string[] | null;
    "languageClaim"?: string;

    /**
     * release, update or preview
     */
    "kind": string;

    /**
     * Avail* constants
     */
    "availability": string;

    /**
     * Transports is the number of validated torrent identities.
     */
    "transports": number;

    /**
     * BrowserOnly: the source offers no torrents; its files open in a
     * browser and can't be downloaded or installed by Seaglass.
     */
    "browserOnly": boolean;

    /**
     * Unresolved explains why mirrors are not usable yet (captcha-required,
     * rate-limited, unsupported host …), one line each.
     */
    "unresolved": string[] | null;
    "warnings": string[] | null;

    /**
     * Newer: a confirmed newer game version than the installed one.
     */
    "newer": boolean;

    /**
     * FeedKey and FeedOffer locate a feed offer for DownloadOffer.
     */
    "feedKey"?: string;
    "feedOffer": number;
}

/**
 * SearchProgress reports remote searches while SearchGames runs.
 */
export interface SearchProgress {
    "text": string;
    "remote": ProviderProgress[] | null;
}

/**
 * SearchResult is the Store's unified search: local matches at once, then
 * the source sites and Steam to fill gaps.
 */
export interface SearchResult {
    "query": BrowseQuery;
    "page": BrowsePage;

    /**
     * Other are Steam games with no known source release ("No known
     * source release"); they can be wishlisted but not installed.
     */
    "other": GameSummary[] | null;
    "remote": ProviderProgress[] | null;

    /**
     * every remote search finished or was skipped
     */
    "complete": boolean;
}

/**
 * SourceStatus is one source's indexing state.
 */
export interface SourceStatus {
    "id": string;
    "name": string;
    "enabled": boolean;

    /**
     * Crawl* constants
     */
    "state": string;
    "releases": number;
    "recentAt": number;

    /**
     * next older page; 0 before the first pass
     */
    "backfillPage": number;
    "backfillDone": boolean;
    "retryAt": number;
    "error"?: string;

    /**
     * What the provider supports (sources.Provider), so setup, filters and
     * status read it instead of naming sources.
     */
    "host": string;

    /**
     * its own site search fills search results
     */
    "search": boolean;

    /**
     * older listing pages exist; false: one finite catalog page
     */
    "paged": boolean;

    /**
     * releases may be installable; false: they open in the browser
     */
    "torrents": boolean;

    /**
     * chosen for a new Store user
     */
    "defaultOn": boolean;

    /**
     * verified limitations, plain sentences
     */
    "notes": string[] | null;
}

/**
 * Status is what discovery is doing, for the Store and Settings.
 */
export interface Status {
    /**
     * Enabled: the Store and source browsing are on and at least one
     * source is chosen.
     */
    "enabled": boolean;

    /**
     * SetupNeeded: an existing Store user must make the one-time source
     * choice before anything is indexed.
     */
    "setupNeeded": boolean;
    "sources": SourceStatus[] | null;

    /**
     * source-backed games in the index
     */
    "games": number;

    /**
     * source articles in the index
     */
    "releases": number;
    "refreshing": boolean;

    /**
     * Paused: the person paused indexing on this PC
     * (StoreSettings.IndexingPaused); nothing is requested until resumed.
     */
    "paused": boolean;

    /**
     * Playing: a game is running, so indexing waits for it to end.
     */
    "playing": boolean;

    /**
     * Stale: the newest listings are older than six hours or their last
     * refresh failed; what is shown is the cached index.
     */
    "stale": boolean;
}
