import { Events, Window } from "@wailsio/runtime";
import { AccountsService, AchievementsService, LaunchService, LibraryService, PadService, ProfileService, SavesService, SettingsService, StoreService, UpdateService } from "../../bindings/github.com/ApolloF/Seaglass/internal/app";
import type { Api } from "./api";
import { normalizeHome } from "./storefront-home";
import type { CompletionCandidate, LibraryCompletion, SteamAccount, WishlistImport, DiscoveryChange, DiscoveryStatus, Enrichment, GameDetails, PreparedRelease, ReviewPage, SearchProgress, SearchResult, StoreHome, WishlistItem, SourceSnapshot, SourceRelease, DownloadLanguageOptions, Accounts, Achievements, AppInfo, ArtChoice, CatalogEntry, CatalogPage, Download, StoreArt, EngineStatus, FeedInfo, Game, MetaState, PadRaw, PadState, Profile, Saves, ScanState, Session, SessionAchievements, Settings, Startup, StoreHit, SyncerStatus, TorrentInterface, UpdateState } from "./types";

// The generated bindings return the Go structs; their JSON matches ./types.
const g = (p: Promise<unknown>) => p as Promise<Game>;

export const realApi: Api = {
  games: () => LibraryService.Games() as Promise<unknown> as Promise<Game[]>,
  scanState: () => LibraryService.ScanState() as Promise<unknown> as Promise<ScanState>,
  rescan: () => LibraryService.Rescan(),
  setFavorite: (id, on) => g(LibraryService.SetFavorite(id, on)),
  setHidden: (id, on) => g(LibraryService.SetHidden(id, on)),
  setPadMode: (id, mode) => g(LibraryService.SetPadMode(id, mode)),
  rename: (id, title) => g(LibraryService.Rename(id, title)),
  confirmMatch: (id) => g(LibraryService.ConfirmMatch(id)),
  chooseExe: (id) => g(LibraryService.ChooseExe(id)),
  openFolder: (id) => LibraryService.OpenFolder(id),
  install: (id) => LibraryService.Install(id),
  metaState: () => LibraryService.MetaState() as Promise<unknown> as Promise<MetaState>,
  refreshMetadata: (id) => LibraryService.RefreshMetadata(id),
  searchSteam: (q) => LibraryService.SearchSteam(q).then((h) => (h ?? []) as unknown as StoreHit[]),
  setMatch: (id, appId, name) => g(LibraryService.SetMatch(id, appId, name)),
  artChoices: (id, kind) => LibraryService.ArtChoices(id, kind).then((c) => (c ?? []) as unknown as ArtChoice[]),
  setArt: (id, kind, art) => g(LibraryService.SetArt(id, kind, art)),
  setCollections: (id, names) => g(LibraryService.SetCollections(id, names)),
  renameCollection: (old, name) => LibraryService.RenameCollection(old, name),
  completion: {
    get: (id, fetch) => LibraryService.Completion(id, fetch) as Promise<unknown> as Promise<LibraryCompletion>,
    candidates: (id, query) => LibraryService.CompletionCandidates(id, query).then((l) => (l ?? []) as unknown as CompletionCandidate[]),
    setMatch: (id, hltbId) => LibraryService.SetCompletionMatch(id, hltbId) as Promise<unknown> as Promise<LibraryCompletion>,
    openLink: (url) => LibraryService.OpenCompletionLink(url),
  },

  settings: () => SettingsService.Get() as Promise<unknown> as Promise<Settings>,
  saveSettings: (s) => SettingsService.Save(s as never) as Promise<unknown> as Promise<Settings>,
  onSettingsChanged: (cb) => Events.On("settings:changed", (e) => cb(e.data as unknown as Settings)),
  addFolder: () => SettingsService.AddFolder() as Promise<unknown> as Promise<Settings>,
  removeFolder: (p) => SettingsService.RemoveFolder(p) as Promise<unknown> as Promise<Settings>,
  autoFolders: () => SettingsService.AutoFolders().then((f) => f ?? []),
  info: () => SettingsService.Info() as Promise<unknown> as Promise<AppInfo>,
  openLog: () => SettingsService.OpenLog(),
  copyDiagnostics: () => SettingsService.CopyDiagnostics(),
  reportProblem: () => SettingsService.ReportProblem(),
  reportUIError: (m) => void SettingsService.ReportUIError(m).catch(() => {}),
  hasSteamGridDBKey: () => SettingsService.HasSteamGridDBKey(),
  setSteamGridDBKey: (k) => SettingsService.SetSteamGridDBKey(k),
  startWithWindows: () => SettingsService.StartWithWindows() as Promise<unknown> as Promise<Startup>,
  setStartWithWindows: (on) => SettingsService.SetStartWithWindows(on) as Promise<unknown> as Promise<Startup>,

  onLibraryChanged: (cb) => Events.On("library:changed", () => cb()),
  onGamesUpdated: (cb) => Events.On("games:updated", (e) => cb((e.data ?? []) as unknown as Game[])),
  onScanState: (cb) => Events.On("scan:state", (e) => cb(e.data as unknown as ScanState)),
  onMetaState: (cb) => Events.On("meta:state", (e) => cb(e.data as unknown as MetaState)),

  store: {
    engine: () => StoreService.Engine() as Promise<unknown> as Promise<EngineStatus>,
    startEngine: () => StoreService.StartEngine() as Promise<unknown> as Promise<EngineStatus>,
    interfaces: () => StoreService.Interfaces().then((i) => (i ?? []) as TorrentInterface[]),
    addresses: (iface) => StoreService.Addresses(iface).then((a) => a ?? []),
    hasProxyPassword: () => StoreService.HasProxyPassword(),
    setProxyPassword: (p) => StoreService.SetProxyPassword(p),
    chooseQBittorrent: () => StoreService.ChooseQBittorrent() as Promise<unknown> as Promise<Settings>,
    getQBittorrent: () => StoreService.GetQBittorrent(),
    downloadsFolder: () => StoreService.DownloadsFolder(),
    chooseDownloadsFolder: () => StoreService.ChooseDownloadsFolder() as Promise<unknown> as Promise<Settings>,
    downloadLanguages: (id) => StoreService.DownloadLanguages(id) as Promise<unknown> as Promise<DownloadLanguageOptions>,
    setDownloadLanguages: (id, language, setupLanguage, ask) => StoreService.SetDownloadLanguages(id, language, setupLanguage, ask) as Promise<unknown> as Promise<Download>,
    discoverReleases: (source, query, resolve) => StoreService.DiscoverReleases(source, query, resolve) as Promise<unknown> as Promise<SourceSnapshot>,
    attachReleaseTorrent: (source, id) => StoreService.AttachReleaseTorrent(source, id) as Promise<unknown> as Promise<SourceRelease>,
    openReleasePage: (source, id) => StoreService.OpenReleasePage(source, id),
    reviewRelease: (source, id, transport) => StoreService.ReviewRelease(source, id, transport),
    downloads: () => StoreService.Downloads().then((d) => (d ?? []) as unknown as Download[]),
    addDownload: (src, title) => StoreService.AddDownload(src, title) as Promise<unknown> as Promise<Download>,
    action: (id, action, del) => StoreService.DownloadAction(id, action as never, del),
    showDownload: (id) => StoreService.ShowDownload(id),
    onDownloads: (cb) => Events.On("store:jobs", (e) => cb((e.data ?? []) as unknown as Download[])),
    onEngine: (cb) => Events.On("store:engine", (e) => cb(e.data as unknown as EngineStatus)),
    feeds: () => StoreService.Feeds().then((f) => (f ?? []) as unknown as FeedInfo[]),
    addFeed: (url) => StoreService.AddFeed(url) as Promise<unknown> as Promise<Settings>,
    removeFeed: (url) => StoreService.RemoveFeed(url) as Promise<unknown> as Promise<Settings>,
    setFeedEnabled: (url, on) => StoreService.SetFeedEnabled(url, on) as Promise<unknown> as Promise<Settings>,
    refreshFeeds: () => StoreService.RefreshFeeds().then((f) => (f ?? []) as unknown as FeedInfo[]),
    catalog: (q) => StoreService.Catalog(q as never).then((p) => ({ entries: (p.entries ?? []) as unknown as CatalogEntry[], total: p.total })) as Promise<CatalogPage>,
    catalogLanguages: () => StoreService.CatalogLanguages().then((l) => l ?? []),
    catalogEntry: (key) => StoreService.CatalogEntry(key) as Promise<unknown> as Promise<CatalogEntry>,
    downloadOffer: (key, offer, opts) => StoreService.DownloadOffer(key, offer, { ...opts, update: !!opts.update }) as Promise<unknown> as Promise<Download>,
    installFolder: (title) => StoreService.InstallFolder(title),
    chooseInstallFolder: (current) => StoreService.ChooseInstallFolder(current),
    gamesFolder: () => StoreService.GamesFolder(),
    chooseGamesFolder: () => StoreService.ChooseGamesFolder() as Promise<unknown> as Promise<Settings>,
    art: (keys) => StoreService.Art(keys).then((a) => (a ?? []) as unknown as StoreArt[]),
    allowDownload: (id, confirm) => StoreService.AllowDownload(id, confirm),
    hasVirusTotalKey: () => StoreService.HasVirusTotalKey(),
    setVirusTotalKey: (k) => StoreService.SetVirusTotalKey(k),
    sandboxAvailable: () => StoreService.SandboxAvailable(),
    updates: () => StoreService.Updates().then((u) => (u ?? []) as unknown as CatalogEntry[]),
    holdDownloads: (on) => StoreService.HoldDownloads(on),
    openInSandbox: (id) => StoreService.OpenInSandbox(id),
    onArt: (cb) => Events.On("store:art", (e) => cb(e.data as unknown as StoreArt)),
    onCatalog: (cb) => Events.On("store:catalog", (e) => cb(e.data as unknown as number)),
    discovery: {
      status: () => StoreService.DiscoveryStatus() as Promise<unknown> as Promise<DiscoveryStatus>,
      setupSources: (sources) => StoreService.SetupSources(sources) as Promise<unknown> as Promise<Settings>,
      refresh: () => StoreService.RefreshDiscovery() as Promise<unknown> as Promise<DiscoveryStatus>,
      pauseIndexing: (paused) => StoreService.PauseIndexing(paused) as Promise<unknown> as Promise<DiscoveryStatus>,
      home: () => (StoreService.StoreHome() as Promise<unknown> as Promise<StoreHome>).then(normalizeHome),
      browse: (q) => StoreService.BrowseGames(q as never) as Promise<unknown> as Promise<SearchResult>,
      search: (q) => StoreService.SearchGames(q as never) as Promise<unknown> as Promise<SearchResult>,
      game: (key) => StoreService.GameDetails(key) as Promise<unknown> as Promise<GameDetails>,
      setSteamMatch: (key, appId, name) => StoreService.SetSteamMatch(key, appId, name) as Promise<unknown> as Promise<GameDetails>,
      prepareRelease: (key, id) => StoreService.PrepareRelease(key, id) as Promise<unknown> as Promise<PreparedRelease>,
      attachTorrent: (key, id) => StoreService.AttachSourceTorrent(key, id) as Promise<unknown> as Promise<PreparedRelease>,
      openRelease: (key, id) => StoreService.OpenSourceRelease(key, id),
      downloadRelease: (key, id, transport, opts) => StoreService.DownloadRelease(key, id, transport, { ...opts, update: !!opts.update }) as Promise<unknown> as Promise<Download>,
      onStatus: (cb) => Events.On("store:discovery", (e) => cb(e.data as unknown as DiscoveryStatus)),
      onGames: (cb) => Events.On("store:games", (e) => cb(e.data as unknown as DiscoveryChange)),
      onSearch: (cb) => Events.On("store:search", (e) => cb(e.data as unknown as SearchProgress)),
    },
    enrich: {
      games: (keys) => StoreService.EnrichGames(keys).then((l) => (l ?? []) as unknown as Enrichment[]),
      game: (key) => StoreService.GameEnrichment(key) as Promise<unknown> as Promise<Enrichment>,
      reviews: (q) => StoreService.GameReviews(q as never) as Promise<unknown> as Promise<ReviewPage>,
      completionCandidates: (key, title) => StoreService.CompletionCandidates(key, title).then((l) => (l ?? []) as unknown as CompletionCandidate[]),
      setCompletionMatch: (key, id) => StoreService.SetCompletionMatch(key, id) as Promise<unknown> as Promise<Enrichment>,
      openLink: (url) => StoreService.OpenStoreLink(url),
      onEnrichment: (cb) => Events.On("store:enrichment", (e) => cb(e.data as unknown as Enrichment)),
    },
    wishlist: {
      list: () => StoreService.Wishlist().then((l) => (l ?? []) as unknown as WishlistItem[]),
      add: (key, title, appId) => StoreService.AddToWishlist(key, title, appId).then((l) => (l ?? []) as unknown as WishlistItem[]),
      remove: (key) => StoreService.RemoveFromWishlist(key).then((l) => (l ?? []) as unknown as WishlistItem[]),
      acknowledge: (key) => StoreService.AcknowledgeWishlist(key).then((l) => (l ?? []) as unknown as WishlistItem[]),
      steamAccount: () => StoreService.SteamWishlistAccount() as Promise<unknown> as Promise<SteamAccount>,
      importSteam: (steamId) => StoreService.ImportSteamWishlist(steamId) as Promise<unknown> as Promise<WishlistImport>,
      onChange: (cb) => Events.On("store:wishlist", (e) => cb((e.data ?? []) as unknown as WishlistItem[])),
    },
  },

  updates: {
    state: () => UpdateService.State() as Promise<unknown> as Promise<UpdateState>,
    check: () => void UpdateService.Check(),
    install: () => UpdateService.Install(),
    openReleasePage: () => UpdateService.OpenReleasePage(),
    onState: (cb) => Events.On("update:state", (e) => cb(e.data as unknown as UpdateState)),
  },

  saves: {
    get: (id, fresh = false) => SavesService.Saves(id, fresh) as Promise<unknown> as Promise<Saves>,
    openSyncer: () => SavesService.OpenSyncer(),
    installSyncer: () => SavesService.InstallSyncer(),
    syncerProject: () => SavesService.SyncerProject(),
    syncer: (start) => SavesService.Syncer(start) as Promise<unknown> as Promise<SyncerStatus>,
  },

  profile: {
    get: (fresh = false) => ProfileService.Get(fresh) as Promise<unknown> as Promise<Profile>,
    switch: (id) => ProfileService.Switch(id) as Promise<unknown> as Promise<Profile>,
    onChange: (cb) => Events.On("profile:changed", (e) => cb(e.data as unknown as Profile)),
  },

  achievements: {
    get: (id, fresh = false) => AchievementsService.Get(id, fresh) as Promise<unknown> as Promise<Achievements>,
    enableUplay: (id) => AchievementsService.EnableUplay(id) as Promise<unknown> as Promise<Achievements>,
    onSession: (cb) => Events.On("achievements:session", (e) => cb(e.data as unknown as SessionAchievements)),
  },

  accounts: {
    get: () => AccountsService.Get() as Promise<unknown> as Promise<Accounts>,
    sync: () => void AccountsService.Sync(),
    setSteamKey: (k) => AccountsService.SetSteamKey(k) as Promise<unknown> as Promise<Accounts>,
    openSteamKeyPage: () => AccountsService.OpenSteamKeyPage(),
    setGOG: (on) => AccountsService.SetGOG(on) as Promise<unknown> as Promise<Accounts>,
    openEpicSignIn: () => AccountsService.OpenEpicSignIn(),
    epicSignIn: (p) => AccountsService.EpicSignIn(p) as Promise<unknown> as Promise<Accounts>,
    epicSignOut: () => AccountsService.EpicSignOut() as Promise<unknown> as Promise<Accounts>,
    openGOGSignIn: () => AccountsService.OpenGOGSignIn(),
    gogSignIn: (p) => AccountsService.GOGSignIn(p) as Promise<unknown> as Promise<Accounts>,
    gogSignOut: () => AccountsService.GOGSignOut() as Promise<unknown> as Promise<Accounts>,
    onChange: (cb) => Events.On("accounts:changed", (e) => cb(e.data as unknown as Accounts)),
  },

  launch: {
    play: (id) => LaunchService.Play(id),
    session: () => LaunchService.Session() as Promise<unknown> as Promise<Session>,
    skip: (id) => void LaunchService.Skip(id),
    answer: (q, o) => void LaunchService.Answer(q, o),
    cancel: () => void LaunchService.Cancel(),
    quitGame: () => LaunchService.QuitGame(),
    setUIMode: (m) => void LaunchService.SetUIMode(m),
    closeOverlay: () => void LaunchService.CloseOverlay(),
    openMain: () => void LaunchService.OpenMain(),
    onSession: (cb) => Events.On("launch:session", (e) => cb(e.data as unknown as Session)),
    onOverlayAction: (cb) =>
      Events.On("overlay:action", (e) => {
        const d = e.data as unknown as { action: string; repeat: boolean };
        cb(d.action, d.repeat);
      }),
    onUIMode: (cb) => Events.On("ui:mode", (e) => cb(e.data as unknown as "desktop" | "bigpicture")),
  },

  window: {
    minimise: () => void Window.Minimise(),
    toggleMaximise: () => void Window.ToggleMaximise(),
    close: () => void Window.Close(),
    fullscreen: (on) => void (on ? Window.Fullscreen() : Window.UnFullscreen()),
  },

  pad: {
    state: () => PadService.State() as Promise<unknown> as Promise<PadState>,
    rumble: (effect) => void PadService.Rumble(effect),
    setLight: (hex) => void PadService.SetLight(hex),
    onAction: (cb) =>
      Events.On("pad:action", (e) => {
        const d = e.data as unknown as { action: string; repeat: boolean };
        cb(d.action, d.repeat);
      }),
    onState: (cb) => Events.On("pad:state", (e) => cb(e.data as unknown as PadState)),
    testInput: (on) => void PadService.TestInput(on),
    onRaw: (cb) => Events.On("pad:raw", (e) => cb(e.data as unknown as PadRaw)),
  },
};
